core/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::group(['middleware' => 'language'], function(){

	Route::get('/', ['as' => 'frontend.home', 'uses' =>'Frontend\HomeFrontendController@index']);
	Route::get('news',['as' => 'frontend.news', 'uses' => 'Frontend\HomeFrontendController@news']);
	Route::get('cara-pemesanan',['as' => 'howOrder', 'uses' => 'Frontend\HomeFrontendController@howOrder']);
	Route::get('search',['as' => 'frontend.search', 'uses' => 'Frontend\HomeFrontendController@search']);
	Route::get('contact-us',['as' => 'frontend.contact', 'uses' => 'Frontend\HomeFrontendController@contact']);
	Route::get('about-us',['as' => 'frontend.about', 'uses' => 'Frontend\HomeFrontendController@about']);
	Route::post('contacts', 'ContactController@store')->name('frontend.contact.store');
	Route::get('locale/{id}', ['as'=>'switchlang','uses' => 'Frontend\LanguageController@switchLang']);
	Route::get('faq', 'Frontend\HomeFrontendController@faq');
	Route::get('brands', 'Frontend\HomeFrontendController@brands')->name('manufacters');
	Route::get('post/detail/{id}', ['as' => 'posts.detail', 'uses' => 'Frontend\HomeFrontendController@postDetail']);
	Route::get('open-pdf/{id}', 'Frontend\HomeFrontendController@downloadPDF')->name('downloadPDF');
	Route::get('cannotbe', function(){
		return url('images/logo.png');
	});
	Auth::routes();
	Route::get('login', function(){return view('errors.404');});
	Route::post('login', function(){return view('errors.404');});
	Route::get('register', function(){return view('errors.404');});
	Route::post('register', function(){return view('errors.404');});
	Route::get('password', function(){return view('errors.404');});
	Route::get('passwords', function(){return view('errors.404');});
	Route::get('password/reset', function(){return view('errors.404');});
	Route::post('password/reset', function(){return view('errors.404');});
	Route::get('password/email', function(){return view('errors.404');});
	Route::post('password/email', function(){return view('errors.404');});

	Route::get('media/{filename}', function($filename) {
        return to_image(storage_path() . '/media/' . $filename);
    })->where(['filename' => '[0-9A-Za-z./\-_ ]+']);

	Route::get('media/files/shares/{filename}', function ($filename) {
		return to_image(storage_path() . '/media/files/shares/' . $filename);
	});
	Route::get('media/images/shares/thumbs/{filename}', function ($filename) {
		return to_image(storage_path() . '/media/images/shares/thumbs/' . $filename);
	});

	Route::group(['prefix' => config('app.backend')], function(){
		Route::get('', 'MyOwnAuth\MyOwnAuthLoginController@index');
		Route::get('login', ['as'=>'moa.login','uses'=>'MyOwnAuth\MyOwnAuthLoginController@login']);
		Route::post('login', ['as'=>'moa.login','uses'=>'MyOwnAuth\MyOwnAuthLoginController@dologin']);
	});
	Route::group(['middleware' => 'auth', 'prefix' => config('app.backend')], function() {
		Route::get('/', function(){
			return redirect()->route('dashboard');
		});
		Route::get('dashboard', ['as'=>'dashboard', 'uses'=>'HomeController@index']);
		Route::resource('items', 'ItemsController');
		Route::resource('brands', 'BrandsController');
		Route::put('settings/changes', ['as'=>'settings.changes', 'uses'=>'SettingsController@changes']);
		Route::get('settings/creator', 'SettingsController@creator');
		Route::resource('settings', 'SettingsController');
		// Route::get('frontSettings/special-offer', 'SettingsController@specialOffer')->name('special_offer');
		Route::get('frontSettings/recom', 'SettingsController@recom')->name('recom');
		Route::get('frontSettings/best-sel', 'SettingsController@bestSel')->name('best_sel');
		Route::get('sections/manage/{id}/list', ['as'=>'sections.manage.list','uses'=>'SectionsController@manage_list']);
		Route::get('sections/manage/{id}/edit/{id_detail}', ['as'=>'sections.manage.edit','uses'=>'SectionsController@manage_edit']);
		Route::put('sections/manage/{id}/edit/{id_detail}', ['as'=>'sections.manage.update','uses'=>'SectionsController@manage_update']);
		Route::delete('sections/manage/{id}/delete/{id_detail}', ['uses'=>'SectionsController@manage_delete'])->name('sections.manage.delete');
		Route::get('sections/creator', ['as'=>'sections.creator','uses'=>'SectionsController@creator']);
		Route::get('sections/manage/{id}', ['as' => 'sections.manage', 'uses'=>'SectionsController@manage']);
		Route::post('sections/manage/{id}', ['as'=>'sections.store_design','uses'=>'SectionsController@store_design']);
		Route::resource('sections', 'SectionsController');
		Route::resource('sectionDetails', 'SectionDetailsController');
		Route::resource('categories', 'CategoriesController');
		Route::resource('posts', 'PostsController');
		Route::resource('users', 'UsersController');
		Route::get('apply', ['as' => 'apply.index', 'uses' => 'ContactController@apply']);
		Route::get('apply/file/{filename}', ['as' => 'apply.file', 'uses' => 'ContactController@file']);
		Route::resource('contacts', 'ContactController');
		Route::get('localizations/set_default', 'LocalizationController@set_default')->name('localizations.set_default');
		Route::resource('localizations', 'LocalizationController');
		Route::resource('sliders', 'SlidersController');
	});
	Route::get('{category}/{id}',['uses' => 'Frontend\HomeFrontendController@product']);
	Route::get('{id}',['as' => 'frontend.product', 'uses' => 'Frontend\HomeFrontendController@product']);
});

core/app/Models/SectionDetails.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class SectionDetails
 * @package App\Models
 * @version March 7, 2017, 6:14 am UTC
 */
class SectionDetails extends Model
{
    use SoftDeletes;

    public $table = 'section_details';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'section_id',
        'content',
        'lang',
        'gen_id'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'section_id' => 'integer',
        'content' => 'string',
        'lang' => 'integer',
        'gen_id' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        
    ];
    
    public function localization() {
        return $this->belongsTo('\App\Models\Localization', 'lang');
    }

}

core/app/Http/Controllers/SectionDetailsController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateSectionDetailsRequest;
use App\Http\Requests\UpdateSectionDetailsRequest;
use App\Repositories\SectionDetailsRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Prettus\Repository\Criteria\RequestCriteria;
use Response;

class SectionDetailsController extends AppBaseController
{
    /** @var  SectionDetailsRepository */
    private $sectionDetailsRepository;

    public function __construct(SectionDetailsRepository $sectionDetailsRepo)
    {
        $this->sectionDetailsRepository = $sectionDetailsRepo;
    }

    /**
     * Display a listing of the SectionDetails.
     *
     * @param Request $request
     * @return Response
     */
    public function index(Request $request)
    {
        $this->sectionDetailsRepository->pushCriteria(new RequestCriteria($request));
        $sectionDetails = $this->sectionDetailsRepository->all();

        return view('section_details.index')
            ->with('sectionDetails', $sectionDetails);
    }

    /**
     * Show the form for creating a new SectionDetails.
     *
     * @return Response
     */
    public function create()
    {
        return view('section_details.create');
    }

    /**
     * Store a newly created SectionDetails in storage.
     *
     * @param CreateSectionDetailsRequest $request
     *
     * @return Response
     */
    public function store(CreateSectionDetailsRequest $request)
    {
        $input = $request->all();

        $sectionDetails = $this->sectionDetailsRepository->create($input);

        Flash::success('Section Details saved successfully.');

        return redirect(route('sectionDetails.index'));
    }

    /**
     * Display the specified SectionDetails.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $sectionDetails = $this->sectionDetailsRepository->findWithoutFail($id);

        if (empty($sectionDetails)) {
            Flash::error('Section Details not found');

            return redirect(route('sectionDetails.index'));
        }

        return view('section_details.show')->with('sectionDetails', $sectionDetails);
    }

    /**
     * Show the form for editing the specified SectionDetails.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $sectionDetails = $this->sectionDetailsRepository->findWithoutFail($id);

        if (empty($sectionDetails)) {
            Flash::error('Section Details not found');

            return redirect(route('sectionDetails.index'));
        }

        return view('section_details.edit')->with('sectionDetails', $sectionDetails);
    }

    /**
     * Update the specified SectionDetails in storage.
     *
     * @param  int              $id
     * @param UpdateSectionDetailsRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateSectionDetailsRequest $request)
    {
        $sectionDetails = $this->sectionDetailsRepository->findWithoutFail($id);

        if (empty($sectionDetails)) {
            Flash::error('Section Details not found');

            return redirect(route('sectionDetails.index'));
        }

        $sectionDetails = $this->sectionDetailsRepository->update($request->all(), $id);

        Flash::success('Section Details updated successfully.');

        return redirect(route('sectionDetails.index'));
    }

    /**
     * Remove the specified SectionDetails from storage.
     *
     * @param  int $id
     *
     * @return Response
     */
    public function destroy($id)
    {
        $sectionDetails = $this->sectionDetailsRepository->findWithoutFail($id);

        if (empty($sectionDetails)) {
            Flash::error('Section Details not found');

            return redirect(route('sectionDetails.index'));
        }

        $this->sectionDetailsRepository->delete($id);

        Flash::success('Section Details deleted successfully.');

        return redirect(route('sectionDetails.index'));
    }
}

core/resources/views/section_details/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Section Details
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'sectionDetails.store']) !!}

                        @include('section_details.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

core/resources/views/section_details/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Section Details
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($sectionDetails, ['route' => ['sectionDetails.update', $sectionDetails->id], 'method' => 'patch']) !!}

                        @include('section_details.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

core/resources/views/section_details/fields.blade.php
<!-- Section Id Field -->
<div class="form-group col-sm-6">
    {!! Form::label('section_id', 'Section Id:') !!}
    {!! Form::number('section_id', null, ['class' => 'form-control']) !!}
</div>

<!-- Content Field -->
<div class="form-group col-sm-12 col-lg-12">
    {!! Form::label('content', 'Content:') !!}
    {!! Form::textarea('content', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('sectionDetails.index') !!}" class="btn btn-default">Cancel</a>
</div>

core/resources/views/section_details/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Section Details</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('sectionDetails.create') !!}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('section_details.table')
            </div>
        </div>
    </div>
@endsection
@section('scripts')
<script type="text/javascript">
    $(document).ready( function () {
        $('#sectionDetails-table').DataTable({
            // "order": [[ 5, "desc" ]]
        });
    });
</script>
@endsection

core/resources/views/section_details/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Section Details
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('section_details.show_fields')
                    <a href="{!! route('sectionDetails.index') !!}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

core/resources/views/section_details/show_fields.blade.php
<!-- Id Field -->
<div class="form-group">
    {!! Form::label('id', 'Id:') !!}
    <p>{!! $sectionDetails->id !!}</p>
</div>

<!-- Section Id Field -->
<div class="form-group">
    {!! Form::label('section_id', 'Section Id:') !!}
    <p>{!! $sectionDetails->section_id !!}</p>
</div>

<!-- Content Field -->
<div class="form-group">
    {!! Form::label('content', 'Content:') !!}
    <p>{!! $sectionDetails->content !!}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{!! $sectionDetails->created_at !!}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{!! $sectionDetails->updated_at !!}</p>
</div>

<!-- Deleted At Field -->
<div class="form-group">
    {!! Form::label('deleted_at', 'Deleted At:') !!}
    <p>{!! $sectionDetails->deleted_at !!}</p>
</div>

core/resources/views/section_details/table.blade.php
<table class="table table-responsive" id="sectionDetails-table">
    <thead>
        <th>Section Id</th>
        <th>Content</th>
        <th>Action</th>
    </thead>
    <tbody>
    @foreach($sectionDetails as $sectionDetails)
        <tr>
            <td>{!! $sectionDetails->section_id !!}</td>
            <td>{!! $sectionDetails->content !!}</td>
            <td>
                {!! Form::open(['route' => ['sectionDetails.destroy', $sectionDetails->id], 'method' => 'delete']) !!}
                <div class='btn-group'>
                    <a href="{!! route('sectionDetails.show', [$sectionDetails->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-eye-open"></i></a>
                    <a href="{!! route('sectionDetails.edit', [$sectionDetails->id]) !!}" class='btn btn-default btn-xs'><i class="glyphicon glyphicon-edit"></i></a>
                    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('Are you sure?')"]) !!}
                </div>
                {!! Form::close() !!}
            </td>
        </tr>
    @endforeach
    </tbody>
</table>